/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $BudgetLimit = {
    properties: {
        created_at: {
            type: 'string',
            isReadOnly: true,
            format: 'date-time',
        },
        updated_at: {
            type: 'string',
            isReadOnly: true,
            format: 'date-time',
        },
        start: {
            type: 'string',
            description: `Start date of the budget limit.`,
            isRequired: true,
            format: 'date-time',
        },
        end: {
            type: 'string',
            description: `End date of the budget limit.`,
            isRequired: true,
            format: 'date-time',
        },
        currency_id: {
            type: 'string',
            description: `Use either currency_id or currency_code. Defaults to the user's default currency.`,
            format: 'string',
        },
        currency_code: {
            type: 'string',
            description: `Use either currency_id or currency_code. Defaults to the user's default currency.`,
            format: 'string',
        },
        currency_name: {
            type: 'string',
            isReadOnly: true,
            format: 'string',
        },
        currency_symbol: {
            type: 'string',
            isReadOnly: true,
            format: 'string',
        },
        currency_decimal_places: {
            type: 'number',
            isReadOnly: true,
            format: 'int32',
        },
        budget_id: {
            type: 'string',
            description: `The budget ID of the associated budget.`,
            isReadOnly: true,
            isRequired: true,
            format: 'string',
        },
        period: {
            type: 'string',
            description: `Period of the budget limit. Only used when auto-generated by auto-budget.`,
            isReadOnly: true,
            isNullable: true,
            format: 'string',
        },
        amount: {
            type: 'string',
            isRequired: true,
            format: 'amount',
        },
        spent: {
            type: 'string',
            isReadOnly: true,
            isNullable: true,
            format: 'amount',
        },
    },
} as const;
