/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $WebhookUpdate = {
    properties: {
        active: {
            type: 'boolean',
            description: `Boolean to indicate if the webhook is active`,
            format: 'boolean',
        },
        title: {
            type: 'string',
            description: `A title for the webhook for easy recognition.`,
            format: 'string',
        },
        secret: {
            type: 'string',
            description: `A 24-character secret for the webhook. It's generated by Firefly III when saving a new webhook. If you submit a new secret through the PUT endpoint it will generate a new secret for the selected webhook, a new secret bearing no relation to whatever you just submitted.`,
            format: 'string',
        },
        trigger: {
            type: 'WebhookTrigger',
        },
        response: {
            type: 'WebhookResponse',
        },
        delivery: {
            type: 'WebhookDelivery',
        },
        url: {
            type: 'string',
            description: `The URL of the webhook. Has to start with \`https\`.`,
            format: 'string',
        },
    },
} as const;
