/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $Webhook = {
    properties: {
        created_at: {
            type: 'string',
            isReadOnly: true,
            format: 'date-time',
        },
        updated_at: {
            type: 'string',
            isReadOnly: true,
            format: 'date-time',
        },
        active: {
            type: 'boolean',
            description: `Boolean to indicate if the webhook is active`,
            format: 'boolean',
        },
        title: {
            type: 'string',
            description: `A title for the webhook for easy recognition.`,
            isRequired: true,
            format: 'string',
        },
        secret: {
            type: 'string',
            description: `A 24-character secret for the webhook. It's generated by Firefly III when saving a new webhook. If you submit a new secret through the PUT endpoint it will generate a new secret for the selected webhook, a new secret bearing no relation to whatever you just submitted.`,
            isReadOnly: true,
            format: 'string',
        },
        trigger: {
            type: 'WebhookTrigger',
            isRequired: true,
        },
        response: {
            type: 'WebhookResponse',
            isRequired: true,
        },
        delivery: {
            type: 'WebhookDelivery',
            isRequired: true,
        },
        url: {
            type: 'string',
            description: `The URL of the webhook. Has to start with \`https\`.`,
            isRequired: true,
            format: 'string',
        },
    },
} as const;
